### 更新 done，不传 title：应该成功
PUT http://localhost:8080/todo/1
Content-Type: application/json

{
  "done": true
}

### 更新为空标题：应该返回 400
PUT http://localhost:8080/todo/1
Content-Type: application/json

{
  "title": "   "
}

### 新增时不传标题：应该返回 400
POST http://localhost:8080/todo
Content-Type: application/json

{
  "done": false
}